"""
Exporters - Export ASCII art to various file formats.
Supports: TXT, HTML, PNG, SVG, JSON
"""

import os
import json
import html


def export_txt(lines: list, filepath: str) -> str:
    """Export ASCII art to plain text file."""
    content = "\n".join(lines)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)
    return filepath


def export_html(lines: list, filepath: str, title: str = "PixelForge ASCII Art",
                font_family: str = "monospace", font_size: str = "14px",
                color: str = "#00ff00", bg_color: str = "#000000") -> str:
    """Export ASCII art to HTML file with styling."""
    escaped_lines = [html.escape(line) for line in lines]
    pre_content = "\n".join(escaped_lines)
    
    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{html.escape(title)}</title>
    <style>
        body {{
            background-color: {bg_color};
            color: {color};
            font-family: {font_family};
            font-size: {font_size};
            line-height: 1.2;
            padding: 20px;
            margin: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            box-sizing: border-box;
        }}
        pre {{
            white-space: pre;
            overflow-x: auto;
            max-width: 100%;
        }}
        .container {{
            text-align: center;
        }}
        .footer {{
            margin-top: 20px;
            font-size: 12px;
            opacity: 0.6;
        }}
    </style>
</head>
<body>
    <div class="container">
        <pre>{pre_content}</pre>
        <div class="footer">Generated by PixelForge-CLI</div>
    </div>
</body>
</html>"""
    
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(html_content)
    return filepath


def export_json(lines: list, filepath: str, metadata: dict = None) -> str:
    """Export ASCII art to JSON format with metadata."""
    data = {
        "version": "1.0",
        "generator": "PixelForge-CLI",
        "lines": lines,
        "width": max(len(line) for line in lines) if lines else 0,
        "height": len(lines),
    }
    if metadata:
        data["metadata"] = metadata
    
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    return filepath


def export_svg(lines: list, filepath: str, font_family: str = "monospace",
               font_size: int = 14, color: str = "#00ff00",
               bg_color: str = "#000000", padding: int = 20) -> str:
    """Export ASCII art to SVG file."""
    if not lines:
        return filepath
    
    line_height = font_size * 1.2
    char_width = font_size * 0.6
    
    max_width = max(len(line) for line in lines) * char_width
    total_height = len(lines) * line_height
    
    svg_width = max_width + padding * 2
    svg_height = total_height + padding * 2
    
    text_elements = []
    for i, line in enumerate(lines):
        y = padding + (i + 1) * line_height
        escaped = html.escape(line)
        text_elements.append(
            f'    <text x="{padding}" y="{y}" '
            f'font-family="{font_family}" font-size="{font_size}" '
            f'fill="{color}">{escaped}</text>'
        )
    
    svg_content = f"""<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" 
     width="{svg_width}" height="{svg_height}" 
     viewBox="0 0 {svg_width} {svg_height}">
  <rect width="100%" height="100%" fill="{bg_color}"/>
  <g>
{chr(10).join(text_elements)}
  </g>
</svg>"""
    
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(svg_content)
    return filepath


def export_png(lines: list, filepath: str, font_family: str = "monospace",
               font_size: int = 14, color: str = "#00ff00",
               bg_color: str = "#000000", padding: int = 20) -> str:
    """Export ASCII art to PNG image. Requires Pillow."""
    try:
        from PIL import Image, ImageDraw, ImageFont
    except ImportError:
        raise ImportError(
            "Pillow is required for PNG export. "
            "Install it with: pip install Pillow"
        )
    
    if not lines:
        return filepath
    
    # Try to find a suitable monospace font
    font = None
    font_paths = [
        "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf",
        "/usr/share/fonts/TTF/DejaVuSansMono.ttf",
        "C:\\Windows\\Fonts\\consola.ttf",
        "C:\\Windows\\Fonts\\cour.ttf",
    ]
    for fp in font_paths:
        if os.path.exists(fp):
            try:
                font = ImageFont.truetype(fp, font_size)
                break
            except Exception:
                continue
    
    if font is None:
        try:
            font = ImageFont.load_default()
        except Exception:
            font = None
    
    # Create image
    line_height = int(font_size * 1.3)
    char_width = int(font_size * 0.6)
    
    max_line_len = max(len(line) for line in lines)
    img_width = max_line_len * char_width + padding * 2
    img_height = len(lines) * line_height + padding * 2
    
    # Parse colors
    bg = _parse_color(bg_color)
    fg = _parse_color(color)
    
    img = Image.new("RGB", (img_width, img_height), bg)
    draw = ImageDraw.Draw(img)
    
    for i, line in enumerate(lines):
        y = padding + i * line_height
        if font:
            draw.text((padding, y), line, fill=fg, font=font)
        else:
            draw.text((padding, y), line, fill=fg)
    
    img.save(filepath)
    return filepath


def _parse_color(color_str: str) -> tuple:
    """Parse a color string to RGB tuple."""
    color_str = color_str.lstrip("#")
    if len(color_str) == 6:
        return tuple(int(color_str[i:i+2], 16) for i in (0, 2, 4))
    elif len(color_str) == 3:
        return tuple(int(c * 2, 16) for c in color_str)
    return (0, 255, 0)


def export(lines: list, filepath: str, format: str = "txt", **kwargs) -> str:
    """
    Export ASCII art to the specified format.
    
    Args:
        lines: ASCII art lines
        filepath: Output file path
        format: Output format ('txt', 'html', 'json', 'svg', 'png')
        **kwargs: Additional format-specific options
        
    Returns:
        Path to the exported file
    """
    format_lower = format.lower().lstrip(".")
    
    exporters = {
        "txt": export_txt,
        "html": export_html,
        "json": export_json,
        "svg": export_svg,
        "png": export_png,
    }
    
    if format_lower not in exporters:
        raise ValueError(
            f"Unsupported format: {format}. "
            f"Supported formats: {', '.join(exporters.keys())}"
        )
    
    # Ensure directory exists
    os.makedirs(os.path.dirname(filepath) if os.path.dirname(filepath) else ".", exist_ok=True)
    
    return exporters[format_lower](lines, filepath, **kwargs)


def list_formats() -> list:
    """List all supported export formats."""
    return ["txt", "html", "json", "svg", "png"]
